name: UbsanAsan
on:
  push:
    branches-ignore:
      - master
      - staging.tmp
      - trying.tmp
      - staging-squash-merge.tmp
  pull_request:
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-san:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: sudo apt-get install clang make -y

      - name: Build and run tests
        run: |
          cd san
          make &> /dev/null || true
          export UBSAN_OPTIONS=log_path=./SAN:print_stacktrace=1:halt_on_errors=0 ASAN_OPTIONS=log_path=./SAN:print_stacktrace=1:check_initialization_order=1:detect_leaks=1:halt_on_errors=0
          ./test
          if test -n "$(find . -maxdepth 1 -name 'SAN.*' -print -quit)"
          then
            cat SAN.*
            exit 1
          fi
